# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002b88dc8cb240e22d2e25c6f9a0703ade24c2dd608d573928d34ca764622fdcf393be675bf8d5ea8556277a48bf3c1a9cb84fb3c4ccf80d30413373dce7242c

test:
  secret_key_base: 37bebf61ed1a605ed6a740ee29173b0e82d7564226fc50a7d47f733a11706918c90d9a1485f51fd01c077c9cd348ffa11bbc2772861bc4e55bb115c4211c6f2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
